version: '3'

tasks:
  build:
    cmds:
      - bash build.sh

  update:
    cmds:
      - nix flake update
      - task: build

  clean:
    cmds:
      - sudo nix-collect-garbage --delete-older-than 7d
