version: '3'

vars:
  GREETING: Hello, World!

tasks:
  rebuild:
    cmds:
      - git add .
      - sudo nixos-rebuild switch --flake . --impure
      - home-manager switch --flake .
      - bash scripts/commit.sh
