version: '3'

tasks:
  build:
    cmds:
      - git add .
      - git diff --staged --name-status
      - sudo nixos-rebuild switch --flake . --impure
      - bash commit.sh

  update:
    cmds:
      - nix flake update
      - task: build

  clean:
    cmds:
      - sudo nix-collect-garbage --delete-older-than 7d
